version: '3.8'
services:
    php-apache:
        container_name: vsnippet-idor-password-reset-15
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            - db-mysql
        volumes:
            - ./vsnippet:/var/www/html/
        ports:
            - 1337:80
    db-mysql:
        container_name: vsnippet-db-mysql-idor-password-reset-15
        volumes:
            - ./config/mysql.sql:/docker-entrypoint-initdb.d/mysql.sql
        image: mysql
        environment:
            MYSQL_DATABASE: ywhvsnippet
            MYSQL_USER: vsnippet
            MYSQL_PASSWORD: vsnippet
            MYSQL_ROOT_PASSWORD: supervulnerableroot
        ports:
            - "1338:3306"
