version: '3.8'
services:
    golang-http:
        container_name: vsnippet-broken-auth-spoof-5
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "127.0.0.1:1337:1337"
